### ISSUE TITLE
Plugin doesn't properly support tests with trailing spaces

### ISSUE THREAD

**Issue by Danon** [eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator#108]
When I name my test like this: (with a trailing space)

```js
import test from 'ava';

test('name ',async  t => {
  t.is('bar', 'bar');
});
```
and I try to run it with `ava -m "name "` it doesn't find the test
```
  × Couldn’t find any matching tests
```

To properly run it, you need to pass it without the space: `ava -m "name"`. The plugin should remove the spaces from the test name.

Additionally, when there are two spaces in the test name:
```js
test('foo   bar',async  t => {
  t.is('bar', 'bar');
});
```

You need to call it with just one space: `ava -m "foo bar"`. Calling it *as-is*, `ava -m "foo  bar"`, then it will fail too.

**Comment by eirikb** [comment]
Thank you for the issue

Do you think a simple 
```kotlin
.trim().replace("  +".toRegex(), " "))
```
would suffice? Feels a bit hacky, but whatever works?

**Comment by Danon** [comment]
> Thank you for the issue
> 
> Do you think a simple
> 
> ```kotlin
> .trim().replace("  +".toRegex(), " "))
> ```
> 
> would suffice? Feels a bit hacky, but whatever works?

For the cases I have found, yes - it will suffice.

I am not entirely positive there aren't any more cases I haven't stumbled upon though.

**Comment by eirikb** [comment]
Is it just me, or does it seem like weird handling of AVA?

Anyway I will make a PR soon.
