### ISSUE TITLE
[feat request]: support setting

### ISSUE THREAD

**Issue by BlackHole1** [eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator#39]
I would like to have a `AVA Test Script` under the `Other Settings` category in settings

Because I don't actually expect him to use `node_modules/.bin/ava`

I want it to be a customizable one so that I can set it to `yarn run test:local`

Because in my project, I will have a lot of preparation work to do before I do unit testing.

see: https://github.com/netless-io/flat-server/blob/main/package.json#L10

----

I tried to write a UI, but I gave up... Because I am not familiar with writing UI in java at all.

> I spent at least 3 hours on this...

**Comment by eirikb** [comment]
That could be possible to make. I have some experience with GUI in Java, but not with IntelliJ, I think that is a bit special.

Curious, how would one go about running a normal matched test in your setup there?
For example a new contributor want to run their new test and only their test from the terminal, how would they go about doing this?

**Comment by eirikb** [comment]
I'm asking because perhaps it can be controlled by some other config? For example can AVA have a prefix config or something? If so the IntelliJ plugin could look for this in known AVA config locations.

**Comment by BlackHole1** [comment]
I have checked the ava documentation and there is no prefix config description

**Comment by BlackHole1** [comment]
hi @eirikb 

I would like to know if there is an estimated development completion time for this?

**Comment by eirikb** [comment]
Nothing in mind. My time for private projects is very limited. And I have other projects I'm already working on.
But if this is very important I could try to work on it soon, perhaps in the weekend.

**Comment by BlackHole1** [comment]
This is more important to me, but it doesn't justify taking up your personal time.
**So just go with your original plan.**
I can use my own build first to go for a temporary solution.

----

**Finally, thank you for your quick response over the past few days and thank you very much for creating this plugin. It lets me develop projects quickly.**

**Comment by eirikb** [comment]
Fixed by #40
