### ISSUE TITLE
AVA 4

### ISSUE THREAD

**Issue by Suyashtnt** [eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator#54]
In AVA 4, cli.js doesnt seem to exist.

**Comment by eirikb** [comment]
Thank you, will look into it.

That's a tricky one, I guess I could make the plugin check file system if it exists.
This means old runs would fail though.

**Comment by eirikb** [comment]
Did some tests, and it seems the new file, `node_modules/ava/lib/cli.js` doesn't work like the old one.
Using `node_modules/.bin/ava` seems to work fine though.
I can't remember, but there was a reason for not using the one in `.bin` before, but perhaps this works now.
How about: Checking for `node_modules/ava/cli.js`, and if not found use `node_modules/.bin/ava`?

**Comment by eirikb** [comment]
https://github.com/eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator/pull/55

**Comment by Suyashtnt** [comment]
before closing an issue merge the PR, could you reopen this while the PR waits to be merged?

**Comment by eirikb** [comment]
Sure. I don't know what the usual approach for issue -> PR is

**Comment by Suyashtnt** [comment]
> Sure. I don't know what the usual approach for issue -> PR is

Basically
in the PR, in the description, simply say closes #issue and when the PR gets merged the issue is closed

**Comment by eirikb** [comment]
> > Sure. I don't know what the usual approach for issue -> PR is
> 
> Basically in the PR, in the description, simply say closes #issue and when the PR gets merged the issue is closed

I don't think I need to, I've linked this issue with the PR, I think it is a new thing.

**Comment by Suyashtnt** [comment]
Now all that's left is to create a new release and we can now AVA 4 in peace :)
