### ISSUE TITLE
Configuration reseting when restarting WebStorm

### ISSUE THREAD

**Issue by max-sv-ma** [eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator#81]
Configuration reseting when restarting WebStorm

Webstorm version: 2021.2

**Comment by eirikb** [comment]
Thanks. Did a test here now and I experienced the same myself.  
I don't use settings myself, but I believe it worked before.  
Any ideas @BlackHole1 ?

**Comment by eirikb** [comment]
After talking to people on Slack it might be that the `AppSettingsState` needs to be more Java-y for IntelliJ to properly serialize/deserialize it. I've been given [this code](https://github.com/AMPivovarov/FastMouseScroll/blob/master/src/main/kotlin/FMSSettings.kt) as example. Tried implementing it as such, but no luck yet.  
Starting to think this might never have worked.  

Will try more things later.

**Comment by eirikb** [comment]
Nevermind, that did the trick. Will make a PR later today

**Comment by BlackHole1** [comment]
> Nevermind, that did the trick. Will make a PR later today

Cool! I'm sorry I haven't been of more help to you 🙇‍♂️. I've been too busy lately... 🥲
