### ISSUE TITLE
ava is shell, but plugin treat it as js

### ISSUE THREAD

**Issue by wenerme** [eirikb/AvaJavaScriptTestRunnerRunConfigurationGenerator#87]
pnpm, monorepo, ava 4.3.3

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
```

maybe caused by pnpm inject NODE_PATH

the ava is

```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/ROOT/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/ROOT/node_modules/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../ava/entrypoints/cli.mjs" "$@"
else
  exec node  "$basedir/../ava/entrypoints/cli.mjs" "$@"
fi
```

**Comment by wenerme** [comment]
Workaround change path to `node_modules/ava/entrypoints/cli.mjs`

**Comment by eirikb** [comment]
I don't quite understand. Plugin tries to execute ava with node, but it should be executed as shell command?
In any case, if the workaround works, do you think this is sufficient, or is the setup you use very common?

**Comment by wenerme** [comment]
I migrate some monorepo to pnpm, every webstorm project need to change this, but this workaround ignore the nearest package.json setting, always exec ava from root (maybe this is another issues), workaround works for now, but if I added some `requires`, have to use `pnpm exec ava` to execute, maybe add one more exec mode is better, currently support node & script, but exec is more portable, npm exec & pnpm exec from nearest package.json should always correct.

run by script should be fine, but plugin run from root & can only use npm.

**Comment by eirikb** [comment]
Not sure how to approach this issue. Is the monorepo of yours public so I can test this out myself, and perhaps see what can be done to add some kind of support in the plugin?

**Comment by wenerme** [comment]
e.g. https://github.com/wenerme/wode

```bash
pnpm install
cat node_modules/.bin/ava
```

node_modules/.bin/ava is a shell script, click a test at subpackage like https://github.com/wenerme/wode/blob/main/packages/system/src/tests/react.test.ts will fail

**Comment by eirikb** [comment]
Hi, sorry for the superlate reply, but I tested this some time ago, and it "Just worked :tm:" for me.  
I checked out the project, ran the commands, opened in IntelliJ, found a random test, tried the keybinding and it ran fine.

**Comment by wenerme** [comment]
I installed ava to root project now, the link is ok, I think installed ava to root project is best, so close this now.
